const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=m=>{const t=$('toast');if(!t)return;t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
const fmt=n=>{if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(1)+' KB';return (n/1048576).toFixed(2)+' MB'};
const slugify=s=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function setupNav(){const b=$('menuBtn'),n=$('navLinks');if(b)b.onclick=()=>n.classList.toggle('open')}

const imageTools=[['compress','Compress Image','Reduce JPG, PNG or WebP size in your browser.'],['resize','Resize Image','Set output width and height.'],['convert','Convert Image','Convert between JPG, PNG and WebP.'],['crop','Crop Image','Center-crop an image to exact pixel dimensions.'],['rotate','Rotate Image','Rotate image by 90°, 180° or 270°.'],['image-pdf','Image to PDF','Turn an image into a downloadable PDF.']];
const pdfTools=[['merge','Merge PDF','Combine multiple PDFs in selected order.'],['split','Split PDF','Extract one page into a new PDF.'],['rotate-pdf','Rotate PDF','Rotate all pages by 90°, 180° or 270°.'],['watermark','Watermark PDF','Add a simple text watermark to every page.'],['compress-pdf','Optimize PDF','Re-save a PDF using object streams.'],['info','PDF Info','Read page count and file size locally.']];
let mode='image',tool='compress',files=[];
function currentMeta(){return [...imageTools,...pdfTools].find(x=>x[0]===tool)||imageTools[0]}
function renderTools(){const list=mode==='image'?imageTools:pdfTools;$('toolPills').innerHTML=list.map(([id,n])=>`<button class="tool-pill ${id===tool?'active':''}" data-tool="${id}">${esc(n)}</button>`).join('');document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;renderTools();updateWorkspace()})}
function updateWorkspace(){const [id,name,desc]=currentMeta();$('wsTitle').textContent=name;$('wsDesc').textContent=desc;$('fileInput').accept=mode==='image'?'image/*':'application/pdf';$('fileInput').multiple=tool==='merge';buildControls();clearFiles()}
function buildControls(){let html='';if(mode==='image'){if(tool==='compress')html='<div class="field"><label>Quality <span id="qualityLabel">78%</span></label><input id="quality" type="range" min="35" max="95" value="78"></div>';if(tool==='resize')html='<div class="field"><label>Width (px)</label><input id="rw" type="number" min="1" value="1200"></div><div class="field"><label>Height (px)</label><input id="rh" type="number" min="1" value="800"></div><div class="field"><label>Output</label><select id="rf"><option value="image/webp">WebP</option><option value="image/jpeg">JPG</option><option value="image/png">PNG</option></select></div>';if(['convert'].includes(tool))html='<div class="field"><label>Output format</label><select id="cf"><option value="image/webp">WebP</option><option value="image/jpeg">JPG</option><option value="image/png">PNG</option></select></div>';if(tool==='crop')html='<div class="field"><label>Crop width (px)</label><input id="cw" type="number" min="1" value="800"></div><div class="field"><label>Crop height (px)</label><input id="ch" type="number" min="1" value="800"></div>';if(tool==='rotate')html='<div class="field"><label>Rotation</label><select id="rot"><option value="90">90°</option><option value="180">180°</option><option value="270">270°</option></select></div>';}else{if(tool==='merge')html='<div class="field"><label>Order</label><input value="Selected file order" disabled></div>';if(tool==='split')html='<div class="field"><label>Page number</label><input id="pageNo" type="number" min="1" value="1"></div>';if(tool==='rotate-pdf')html='<div class="field"><label>Rotation</label><select id="prot"><option value="90">90°</option><option value="180">180°</option><option value="270">270°</option></select></div>';if(tool==='watermark')html='<div class="field"><label>Watermark text</label><input id="wm" value="ToolNest"></div><div class="field"><label>Opacity</label><input id="op" type="number" min="0" max="1" step="0.1" value="0.3"></div>';} $('controls').innerHTML=html;const q=$('quality');if(q)q.oninput=()=>{$('qualityLabel').textContent=q.value+'%'}}
function clearFiles(){$('fileInput').value='';files=[];$('fileList').innerHTML='';$('result').className='result';$('result').innerHTML=''}
function listFiles(){ $('fileList').innerHTML=files.map((f,i)=>`<div class="file-row"><div style="min-width:0"><div class="file-name">${esc(f.name)}</div><div class="file-meta">${fmt(f.size)} • ${esc(f.type||'unknown')}</div></div><button class="btn secondary" data-remove="${i}">Remove</button></div>`).join('')+(files.length&&tool==='merge'?`<button class="btn primary" id="processBtn">Merge ${files.length} PDFs</button>`:'');document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{files.splice(Number(b.dataset.remove),1);listFiles()});const p=$('processBtn');if(p)p.onclick=processCurrent}
function acceptFiles(fs){files=mode==='image'?fs.slice(0,1):(tool==='merge'?fs:fs.slice(0,1));listFiles();if(files.length&&tool!=='merge')processCurrent()}
function setupDrop(){const d=$('dropzone');if(!d)return;['dragenter','dragover'].forEach(e=>d.addEventListener(e,x=>{x.preventDefault();d.classList.add('drag')}));['dragleave','drop'].forEach(e=>d.addEventListener(e,x=>{x.preventDefault();d.classList.remove('drag')}));d.addEventListener('drop',e=>acceptFiles([...e.dataTransfer.files]));$('pickBtn').onclick=()=>$('fileInput').click();$('fileInput').onchange=e=>acceptFiles([...e.target.files])}
function blobFromCanvas(c,m,q){return new Promise(r=>c.toBlob(r,m,q))}
function loadImage(f){return new Promise((resolve,reject)=>{const img=new Image();const u=URL.createObjectURL(f);img.onload=()=>{URL.revokeObjectURL(u);resolve(img)};img.onerror=reject;img.src=u})}
function ext(m){return m==='image/png'?'png':m==='image/jpeg'?'jpg':'webp'}
async function processImage(f){const img=await loadImage(f);let w=img.width,h=img.height,out='image/webp',q=.78;if(tool==='compress'){q=Number($('quality').value)/100;const s=Math.min(1,1800/Math.max(w,h));w=Math.max(1,Math.round(w*s));h=Math.max(1,Math.round(h*s))}if(tool==='resize'){w=Math.max(1,Number($('rw').value)||w);h=Math.max(1,Number($('rh').value)||h);out=$('rf').value;q=.88}if(tool==='convert'){out=$('cf').value;q=.9}if(tool==='crop'){w=Math.min(w,Math.max(1,Number($('cw').value)||w));h=Math.min(h,Math.max(1,Number($('ch').value)||h))}if(tool==='rotate'){const d=Number($('rot').value);if(d===90||d===270)[w,h]=[h,w]}const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');if(tool==='rotate'){const d=Number($('rot').value);x.translate(w/2,h/2);x.rotate(d*Math.PI/180);x.drawImage(img,-img.width/2,-img.height/2)}else if(tool==='crop'){const sx=Math.max(0,(img.width-w)/2),sy=Math.max(0,(img.height-h)/2);x.drawImage(img,sx,sy,w,h,0,0,w,h)}else{x.drawImage(img,0,0,w,h)}const b=await blobFromCanvas(c,out,q);return{blob:b,name:`toolnest-${f.name.replace(/\.[^.]+$/,'')}.${ext(out)}`,msg:`Created ${w}×${h} ${ext(out).toUpperCase()} output (${fmt(b.size)}).`}}
async function imageToPdf(f){if(!window.PDFLib)throw Error('PDF library unavailable');const bytes=await f.arrayBuffer();const img=await createImageBitmap(f);const pdf=await PDFLib.PDFDocument.create();const page=pdf.addPage([img.width,img.height]);const em=f.type==='image/png'?await pdf.embedPng(bytes):await pdf.embedJpg(bytes);page.drawImage(em,{x:0,y:0,width:img.width,height:img.height});const b=await pdf.save();return{blob:new Blob([b],{type:'application/pdf'}),name:`toolnest-${f.name.replace(/\.[^.]+$/,'')}.pdf`,msg:`Created a ${img.width}×${img.height} PDF.`}}
async function processPdf(){if(!window.PDFLib)throw Error('PDF library unavailable');if(tool==='merge'){const out=await PDFLib.PDFDocument.create();for(const f of files){const d=await PDFLib.PDFDocument.load(await f.arrayBuffer());for(const p of await out.copyPages(d,d.getPageIndices()))out.addPage(p)}const b=await out.save();return{blob:new Blob([b],{type:'application/pdf'}),name:'toolnest-merged.pdf',msg:`Merged ${files.length} PDFs into one file (${fmt(b.length)}).`}}const src=files[0],d=await PDFLib.PDFDocument.load(await src.arrayBuffer());if(tool==='info')return{info:true,msg:`${d.getPageCount()} pages • ${fmt(src.size)} source file.`};if(tool==='split'){const n=Math.min(d.getPageCount(),Math.max(1,Number($('pageNo').value)||1));const out=await PDFLib.PDFDocument.create();const [p]=await out.copyPages(d,[n-1]);out.addPage(p);const b=await out.save();return{blob:new Blob([b],{type:'application/pdf'}),name:`toolnest-page-${n}.pdf`,msg:`Extracted page ${n}.`}}if(tool==='rotate-pdf'){const deg=Number($('prot').value);d.getPages().forEach(p=>p.setRotation(PDFLib.degrees((p.getRotation().angle||0)+deg)));const b=await d.save();return{blob:new Blob([b],{type:'application/pdf'}),name:'toolnest-rotated.pdf',msg:`Rotated ${d.getPageCount()} pages by ${deg}°.`}}if(tool==='watermark'){const text=$('wm').value||'ToolNest',op=Math.max(0,Math.min(1,Number($('op').value)||.3));d.getPages().forEach(p=>{const {width,height}=p.getSize();p.drawText(text,{x:Math.max(10,width/2-50),y:height/2,size:26,color:PDFLib.rgb(.25,.25,.25),opacity:op,rotate:PDFLib.degrees(35)})});const b=await d.save();return{blob:new Blob([b],{type:'application/pdf'}),name:'toolnest-watermarked.pdf',msg:`Watermarked ${d.getPageCount()} pages.`}}throw Error('Unsupported PDF operation')}
async function processCurrent(){if(!files.length){toast('Choose a file first');return}try{let r;if(mode==='image'&&tool==='image-pdf')r=await imageToPdf(files[0]);else if(mode==='image')r=await processImage(files[0]);else r=await processPdf();$('result').className='result show';if(r.info){$('result').innerHTML=`<strong>Done</strong><div class="muted">${esc(r.msg)}</div>`}else{const u=URL.createObjectURL(r.blob);$('result').innerHTML=`<strong>Done</strong><div class="muted" style="margin:5px 0 11px">${esc(r.msg)}</div><a class="btn primary" href="${u}" download="${esc(r.name)}">Download result</a>`}toast('Tool completed')}catch(e){console.error(e);$('result').className='result show';$('result').innerHTML='<strong>Could not process the file</strong><div class="muted">Check the format, file size and try again.</div>'}}
function setupWorkspace(){if(!$('workspace'))return;document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;tool=mode==='image'?'compress':'merge';document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x.dataset.mode===mode));renderTools();updateWorkspace()});setupDrop();renderTools();updateWorkspace()}

const aiActions={summarize:t=>t.split(/\s+/).slice(0,55).join(' ')+(t.split(/\s+/).length>55?'…':''),rewrite:t=>`Rewritten version:\n\n${t.trim()}\n\nTone can be customized after connecting an AI provider.`,title:t=>{const s=t.replace(/[^a-zA-Z0-9 ]/g,' ').trim().split(/\s+/).slice(0,8).join(' ');return s?`Suggested title: ${s}`:'Suggested title: Untitled content'},translate:t=>`Translation demo:\n\n${t}\n\nConnect an AI provider for production translation.`};
function setupAI(){const action=$('aiAction');if(!action)return;const run=()=>{const t=$('aiInput').value.trim();if(!t){toast('Enter some text first');return}const fn=aiActions[action.value]||aiActions.summarize;$('aiOutput').value=fn(t);toast('AI utility completed in demo mode')};$('runAI').onclick=run;$('copyAI').onclick=async()=>{try{await navigator.clipboard.writeText($('aiOutput').value);toast('Copied')}catch{toast('Copy unavailable')}}}

const products=[{id:'excel-cleaner',name:'Excel Data Cleaning Pack',desc:'Ready-to-use sheets for duplicates, formatting and cleanup workflows.',price:99,icon:'XLSX'},{id:'invoice-pack',name:'Small Business Invoice Pack',desc:'Editable invoice and quotation templates for everyday business work.',price:149,icon:'INV'},{id:'prompt-pack',name:'AI Productivity Prompt Pack',desc:'Practical prompts for research, writing and admin tasks.',price:79,icon:'AI'},{id:'pdf-kit',name:'PDF Workflow Checklist',desc:'Printable checklist for organizing, reviewing and sharing PDF files.',price:49,icon:'PDF'}];
function getCart(){return JSON.parse(localStorage.getItem('toolnest-cart')||'[]')}function setCart(c){localStorage.setItem('toolnest-cart',JSON.stringify(c))}function updateCartCount(){const n=getCart().reduce((a,x)=>a+x.qty,0);document.querySelectorAll('[data-cart-count]').forEach(x=>x.textContent=n)}function addToCart(id){const c=getCart(),p=c.find(x=>x.id===id);if(p)p.qty++;else c.push({id,qty:1});setCart(c);updateCartCount();toast('Product added to cart')}
function renderProducts(){const root=$('productGrid');if(!root)return;root.innerHTML=products.map(p=>`<article class="card"><div class="product-thumb">${esc(p.icon)}</div><h3>${esc(p.name)}</h3><p>${esc(p.desc)}</p><div class="product-meta"><span class="price-sm">₹${p.price}</span><button class="btn primary" data-add="${p.id}">Add</button></div></article>`).join('');document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addToCart(b.dataset.add));updateCartCount()}
function setupCart(){const box=$('cartBox');if(!box)return;const render=()=>{const c=getCart();if(!c.length){box.innerHTML='<div class="muted">Your cart is empty.</div>';return}const rows=c.map(x=>{const p=products.find(p=>p.id===x.id);return `<div class="file-row"><div><div class="file-name">${esc(p.name)}</div><div class="file-meta">Qty ${x.qty} • ₹${p.price*x.qty}</div></div><button class="btn secondary" data-del="${x.id}">Remove</button></div>`}).join('');const total=c.reduce((s,x)=>s+products.find(p=>p.id===x.id).price*x.qty,0);box.innerHTML=rows+`<div style="display:flex;justify-content:space-between;margin-top:13px"><strong>Total</strong><strong>₹${total}</strong></div><button class="btn dark" id="checkoutBtn" style="margin-top:12px;width:100%">Checkout setup required</button>`;document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{setCart(c.filter(x=>x.id!==b.dataset.del));render();updateCartCount()});$('checkoutBtn').onclick=()=>toast('Connect Razorpay/Stripe in production before taking payments')};render()}

function setupAutomation(){const input=$('csvInput');if(!input)return;const clean=()=>{const raw=$('csvInput').value.trim();if(!raw){toast('Paste CSV data first');return}const lines=raw.split(/\r?\n/).filter(Boolean);const rows=lines.map(x=>x.split(',').map(s=>s.trim()));const seen=new Set(),out=[];rows.forEach(r=>{const k=r.join('\u001f').toLowerCase();if(!seen.has(k)){seen.add(k);out.push(r)}});$('csvOutput').value=out.map(r=>r.join(',')).join('\n');$('csvStats').textContent=`${rows.length} rows → ${out.length} unique rows`;toast('CSV cleaned')};$('cleanCsv').onclick=clean;$('downloadCsv').onclick=()=>{const b=new Blob([$ ('csvOutput').value],{type:'text/csv'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download='toolnest-cleaned.csv';a.click();URL.revokeObjectURL(u)} }

function setupAnalytics(){document.querySelectorAll('[data-year]').forEach(x=>x.textContent=new Date().getFullYear())}
setupNav();setupWorkspace();setupAI();renderProducts();setupCart();setupAutomation();setupAnalytics();
